"use client";
import { BackButton } from "@/components/ui/back-button";
import { Footer } from "./Footer";

interface TermsOfServiceProps {
  onBack: () => void;
  onNavigate?: (page: string) => void;
}

export function TermsOfService({ onBack, onNavigate }: TermsOfServiceProps) {
  return (
    <div className="min-h-screen bg-[#1a1a3e] flex flex-col">
      <div className="max-w-4xl mx-auto px-4 py-6 md:py-12 flex-1">
        <BackButton onClick={onBack} />
        <h1 className="text-3xl md:text-4xl font-bold text-white mb-4 md:mb-8">Terms of Service</h1>
        <div className="prose prose-invert max-w-none space-y-6">
          <p className="text-white/80">Last updated: March 1, 2026</p>

          <h2 className="text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
          <p className="text-white/80">By creating an account or using First Day, you agree to these terms. If you do not agree, please do not use the service.</p>

          <h2 className="text-2xl font-semibold text-white">2. Description of Service</h2>
          <p className="text-white/80">First Day is a goal achievement platform that uses AI to generate personalized 30-day plans with daily activities, resource recommendations, and progress tracking. Plans are tailored to your stated goals, experience level, and preferences.</p>

          <h2 className="text-2xl font-semibold text-white">3. User Accounts</h2>
          <p className="text-white/80">You are responsible for maintaining the security of your account credentials. You must provide accurate information when creating your account. You may not share your account with others or create multiple accounts.</p>

          <h2 className="text-2xl font-semibold text-white">4. AI-Generated Content</h2>
          <p className="text-white/80">Plans, activities, and recommendations generated by First Day are created using artificial intelligence. While we strive for quality and relevance, AI-generated content:</p>
          <ul className="list-disc pl-6 text-white/80 space-y-1">
            <li>Is provided as guidance and suggestions, not professional advice</li>
            <li>May not be perfectly accurate or suitable for every individual</li>
            <li>Should not replace professional medical, fitness, financial, or legal advice</li>
            <li>May include links to third-party resources that we do not control or endorse</li>
          </ul>
          <p className="text-white/80">You are responsible for evaluating whether any suggested activities are appropriate for your situation.</p>

          <h2 className="text-2xl font-semibold text-white">5. Content Ownership</h2>
          <p className="text-white/80">You retain ownership of any content you create on First Day, including your goals, reflections, and progress notes. By using the service, you grant us a limited license to store and process your content solely for the purpose of providing the service to you. AI-generated plans are provided for your personal use.</p>

          <h2 className="text-2xl font-semibold text-white">6. Acceptable Use</h2>
          <p className="text-white/80">You agree not to:</p>
          <ul className="list-disc pl-6 text-white/80 space-y-1">
            <li>Misuse the service or attempt to access other users&apos; data</li>
            <li>Use the service for any illegal purpose</li>
            <li>Attempt to reverse engineer, scrape, or extract data from the service</li>
            <li>Use automated tools to access the service beyond normal usage</li>
          </ul>

          <h2 className="text-2xl font-semibold text-white">7. Service Availability</h2>
          <p className="text-white/80">We aim to keep First Day available and reliable, but we do not guarantee uninterrupted access. The service may be temporarily unavailable for maintenance, updates, or due to circumstances beyond our control. We reserve the right to modify, suspend, or discontinue features of the service with reasonable notice.</p>

          <h2 className="text-2xl font-semibold text-white">8. Account Termination</h2>
          <p className="text-white/80">You may delete your account at any time through the Settings page. We may suspend or terminate accounts that violate these terms. Upon termination, your data will be deleted in accordance with our Privacy Policy.</p>

          <h2 className="text-2xl font-semibold text-white">9. Limitation of Liability</h2>
          <p className="text-white/80">First Day is provided &quot;as is&quot; without warranties of any kind, either express or implied. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to any outcomes from following AI-generated plans or recommendations.</p>

          <h2 className="text-2xl font-semibold text-white">10. Changes to Terms</h2>
          <p className="text-white/80">We may update these terms from time to time. We will notify you of material changes by posting the updated terms on this page. Continued use of the service after changes constitutes acceptance of the new terms.</p>

          <h2 className="text-2xl font-semibold text-white">11. Contact</h2>
          <p className="text-white/80">For questions about these terms, contact us at <a href="mailto:support@firstday.life" className="text-white font-bold hover:underline">support@firstday.life</a>.</p>
        </div>
      </div>
      <Footer onPrivacyClick={() => onNavigate?.("privacy")} />
    </div>
  );
}
