"use client";
import type { Artifact, ArtifactKind } from "@/types";
import { GuitarTab } from "@/components/GuitarTab";

/**
 * ArtifactSlot — renders whatever structured thing an activity carries.
 *
 * The renderer half of the artifact seam. Adding a domain is one line in
 * RENDERERS; DayView never changes and never learns what a riff is.
 *
 * Unknown kinds render NOTHING, on purpose. A plan stored before a renderer
 * existed, or one generated by a newer model, must degrade to its activity text
 * rather than throwing inside the day the user is trying to work through.
 */
const RENDERERS: { [K in ArtifactKind]: (a: Extract<Artifact, { kind: K }>) => React.ReactNode } = {
  "guitar-riff": (a) => <GuitarTab riff={a.data} />,
};

export function ArtifactSlot({ artifact }: { artifact: Artifact | null }) {
  if (!artifact) return null;
  const render = RENDERERS[artifact.kind];
  if (!render) return null;
  // The activity row is a <label> wrapping a checkbox, so a click anywhere in it
  // toggles completion. Interacting with the artifact must not tick the box.
  return <div onClick={(e) => e.preventDefault()}>{render(artifact as never)}</div>;
}
